# Generated by Django 4.2.5 on 2023-10-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('admin_id', models.IntegerField(db_column='Admin_ID', primary_key=True, serialize=False)),
                ('admin_name', models.CharField(db_column='Admin_Name', max_length=45)),
                ('admin_dept', models.CharField(db_column='Admin_Dept', max_length=45)),
                ('admin_contact', models.IntegerField(db_column='Admin_Contact', unique=True)),
                ('admin_email', models.CharField(db_column='Admin_Email', max_length=45, unique=True)),
                ('admin_address', models.CharField(db_column='Admin_Address', max_length=45)),
                ('admin_login_password', models.CharField(db_column='Admin_Login_Password', max_length=45, unique=True)),
            ],
            options={
                'db_table': 'admin_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('alert_id', models.IntegerField(db_column='Alert_ID', primary_key=True, serialize=False)),
                ('alert_dept', models.CharField(db_column='Alert_DEPT', max_length=45)),
                ('alert_notification', models.CharField(db_column='ALERT_notification', max_length=150)),
                ('alert_state', models.CharField(db_column='Alert_State', max_length=45)),
                ('alert_type', models.CharField(db_column='ALERT_type', max_length=45)),
            ],
            options={
                'db_table': 'alerts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyContacts',
            fields=[
                ('idemergency_contacts', models.IntegerField(db_column='idEmergency_contacts', primary_key=True, serialize=False)),
                ('emergency_contact_type', models.CharField(db_column='Emergency_Contact_type', max_length=45)),
                ('emergency_number', models.IntegerField(db_column='Emergency_Number', unique=True)),
                ('emergency_precautions', models.CharField(db_column='Emergency_Precautions', max_length=150)),
            ],
            options={
                'db_table': 'emergency_contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsUpdates',
            fields=[
                ('news_id', models.IntegerField(db_column='News_ID', primary_key=True, serialize=False)),
                ('news_updates_dept', models.CharField(db_column='News&Updates_Dept', max_length=45)),
                ('news', models.CharField(blank=True, db_column='News', max_length=150, null=True)),
                ('updates', models.CharField(blank=True, db_column='Updates', max_length=150, null=True)),
            ],
            options={
                'db_table': 'news&updates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrecautionaryAdvisory',
            fields=[
                ('idprecautionary_advisory', models.IntegerField(db_column='idPrecautionary_advisory', primary_key=True, serialize=False)),
                ('precautionary_advisory', models.CharField(db_column='Precautionary_advisory', max_length=45)),
                ('precautionary_advisory_state', models.CharField(db_column='Precautionary_advisory_state', max_length=45)),
                ('precautionary_advisory_dos', models.CharField(db_column='Precautionary_advisory_DOs', max_length=45)),
                ('precautionary_advisory_donts', models.CharField(db_column='Precautionary_advisory_DONTs', max_length=45)),
            ],
            options={
                'db_table': 'precautionary_advisory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schemes',
            fields=[
                ('schemes_id', models.IntegerField(db_column='Schemes_ID', primary_key=True, serialize=False)),
                ('schemes_type', models.CharField(db_column='Schemes_Type', max_length=45)),
                ('schemes_data', models.CharField(db_column='Schemes_Data', max_length=45)),
                ('schemes_location', models.CharField(db_column='Schemes_Location', max_length=45)),
            ],
            options={
                'db_table': 'schemes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('idtraining_data', models.IntegerField(db_column='idTraining_Data', primary_key=True, serialize=False)),
                ('training_type', models.CharField(db_column='Training_type', max_length=45)),
                ('training_area', models.CharField(db_column='Training_Area', max_length=45)),
                ('training_info', models.CharField(db_column='Training_Info', max_length=150)),
                ('training_dept', models.CharField(db_column='training_Dept', max_length=45)),
            ],
            options={
                'db_table': 'training_data',
                'managed': False,
            },
        ),
    ]
