# Generated by Django 4.2.5 on 2023-10-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_admindata_alerts_emergencycontacts_newsupdates_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminData',
        ),
        migrations.DeleteModel(
            name='Alerts',
        ),
        migrations.DeleteModel(
            name='EmergencyContacts',
        ),
        migrations.DeleteModel(
            name='NewsUpdates',
        ),
        migrations.DeleteModel(
            name='PrecautionaryAdvisory',
        ),
        migrations.DeleteModel(
            name='Schemes',
        ),
        migrations.DeleteModel(
            name='TrainingData',
        ),
    ]
