# Generated by Django 4.2.5 on 2023-10-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_admin_details_alerts_dept_emergency_contacts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin_details',
            options={'managed': False, 'verbose_name_plural': 'Admin_Details'},
        ),
    ]
